apiVersion: v1
kind: Service
metadata:
  name: edqos-app
  labels:
    app: edqos
spec:
  type: LoadBalancer
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
  selector:
    app: edqos
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: edqos-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: edqos
    spec:
      containers:
      - name: edqos-app
        image: mbrainar/edqos_app:latest
        ports:
        - containerPort: 5001
        env:
        - name: APIC_SERVER
          value: <YOUR SERVER HERE>
        - name: APIC_USERNAME
          value: <YOUR USERNAME HERE>
        - name: APIC_PASSWORD
          value: <YOUR PASSWORD HERE>
